version: '3.8'

services:
  ksi-be:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: fi0ksi/ksi-be
    ports:
      - "3030:3030"
    volumes:
      - ./.docker/data/db:/opt/database
      - ./.docker/data/data:/opt/data
      - ./.docker/data/seminar.git:/opt/seminar.git  # Not needed if SEMINAR_GIT_URL is set to value other than ::local::
#      - ./config.py:/opt/web-backend/config.py
    environment:
      - SEMINAR_GIT_URL=${SEMINAR_GIT_URL:-::local::}  #  If set to value other than ::local::, clones seminar repository from this origin instead of creating a blank one
    container_name: ksi-be
    devices:
      - /dev/fuse:/dev/fuse
    cap_add:
      - SYS_ADMIN
    privileged: true
    security_opt:
      - apparmor:unconfined
    entrypoint: ["/bin/bash", "./.docker/entrypoint.sh"]
  ksi-fe-dev:
    container_name: ksi-fe-local
    image: fi0ksi/ksi-fe-local
    ports:
      - "4201:80"
  ksi-fe-old-dev:
    container_name: ksi-fe-old-dev
    image: fi0ksi/ksi-fe-old-local
    ports:
      - "8080:80"
